---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Windsurf configuration
windsurf_download_url: "https://github.com/codeium/windsurf/releases/latest/download/Windsurf.dmg"

# Git repositories to clone
git_repositories:
  - name: fabric
    repo: https://github.com/danielmiessler/fabric.git
    version: main

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  # - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Freeform
  - Reminders
  - Contacts
  - Notes
  - Maps
dockitems_persist:
  # - name: "Sublime Text"
  #   path: "/Applications/Sublime Text.app/"
  #   pos: 5
  - name: "System Settings"
    path: "/Applications/System Settings.app/"
    pos: 3
  - name: "Arc"
    path: "/Applications/Arc.app"

configure_sudoers: true
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password for specific commands
  %admin ALL=(ALL) NOPASSWD: /opt/homebrew/bin/brew
  %admin ALL=(ALL) NOPASSWD: /usr/sbin/installer
  %admin ALL=(ALL) NOPASSWD: /usr/bin/xcode-select
  %admin ALL=(ALL) NOPASSWD: /usr/bin/xcodebuild

dotfiles_repo: https://github.com/AdamPippert/dotfiles.git
dotfiles_repo_version: main  # this is now the default post 2020
dotfiles_repo_accept_hostkey: false
dotfiles_repo_local_destination: ~/Development/dotfiles
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .gitignore
  # - .inputrc
  - .osx
  - .vimrc
  - .emacs
  - .yabairc
  - .config
  - .windsurf

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - antigen
  # - asdf # Installed via shell
  - autoconf
  - awscli
  - azure-cli
  - bash-completion
  - certbot
  - coreutils
  - doxygen
  - emacs
  - evince
  - fd
  - fzf
  - ffmpeg
  - gawk
  - gettext
  - gifsicle
  - git
  - gh
  - go
  - gpg
  - gnuplot
  - httpie
  - iperf
  - ipython
  - jq
  - jupyterlab
  - kafka
  - lazygit
  - ledger
  - libcaca
  - libevent
  - lolcat
  - lua
  - ncurses
  - sqlite
  - nmap
  - node
  - nvim
  - nvm
  - octave
  - php
  - podman
  - podman-compose
  - ripgrep
  - rust
  - koekeishiya/formulae/skhd
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - tmux
  - koekeishiya/formulae/yabai
  - yarn
  - yt-dlp
  - wget
  - wrk
  - zoxide
#  - zsh-history-substring-search

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - basictex
  - chromedriver-beta
  - docker
  #  - firefox - installed by corporate tool
  - gimp
  #  - google-chrome - installed by corporate tool
  - handbrake
  - keycastr
  - kitty
  - licecap
  - obs
  # - podman-desktop - installed by standalone download pre-script
  - sequel-ace
  - slack
  - transmit
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Desktop customization
default_wallpaper: tokyo-street.heic

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages:
  #  - name: webpack
  #    state: present # present/absent/latest, default: present
  #    version: "^2.6" # default: N/A
  - name: "@ansible/ansible-language-server"
    state: latest

pip_packages:
  - name: ansible
    state: present
    version: "9.3.0"  # Latest stable version as of Feb 2024
  - name: ansible-rulebook
    state: present
  - name: langchain
    state: present
    version: "0.1.9"  # Latest stable version as of Feb 2024
  - name: openai
    state: latest
  - name: gmail
    state: present
  - name: Sphinx
    state: present
  - name: gunicorn
    state: present
  - name: django
    state: present
    version: "5.0.2"  # Latest LTS version as of Feb 2024
  - name: jmespath
    state: present
  - name: pypdf
    state: present
  - name: toml
    state: present
  - name: pygpt4all
    state: present
  - name: chromadb
    state: present
    version: "0.4.22"  # Latest stable version as of Feb 2024
  - name: pdf2image
    state: present
  - name: gpt4all
    state: latest
  - name: pydo
    state: latest
  - name: pydantic
    state: present
    version: "2.6.1"  # Latest stable version as of Feb 2024
  - name: rich
    state: latest
  - name: instabot
    state: latest
  - name: tweepy
    state: latest
  - name: ollama
    state: latest

cargo_packages: []
  #  - name: rustup
  #  state: latest
  #- name: clippy
  #  state: latest
  #- name: dotenvy
  #  state: latest
  #- name: prost
  #  state: latest

# Set to 'true' to configure Sublime Text.
configure_sublime: false
# sublime_base_path: '~/Library/Application Support/Sublime Text'
# sublime_config_path: "Packages/User"
# sublime_package_control:
#  - "DocBlockr"
#  - "Dockerfile Syntax Highlighting"
#  - "FileDiffs"
#  - "GitHub Flavored Markdown Preview"
#  - "Jinja2"
#  - "Package Control"
#  - "PHP-Twig"
#  - "Pretty JSON"
#  - "SublimeLinter"
#  - "SublimeLinter-contrib-yamllint"
#  - "TrailingSpaces"
#  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
